### ISSUE TITLE
Association classname?

### ISSUE THREAD

**Issue by tvongaza** [peritor/simply_stored#1]
Is there any way to have more then on association point to another simply stored item?

IE can we do the following:

```
class Document
  include SimplyStored::Couch

  belongs_to :creator, :classname => "User"
  belongs_to :updater, :classname => "User"

end
```

**Comment by jweiss** [comment]
now, currently not. But it shouldn't be too hard to implement it. Currently everything uses the singular form of the belongs_to as the Class.

It would be great if you could submit a patch.

**Comment by peritor** [comment]
I've just merged some patches that allow you to just do that.
