### ISSUE TITLE
Exception on comparison with foreign object

### ISSUE THREAD

**Issue by d5e** [peritor/simply_stored#5]
I ran into this error when I was doing an myarray.include?(:some_symbol)

myarray holds some SimplyStored Documents ... when comparing of those it raises an 

```
undefined method `_id' for :mySymbol:Symbol
/usr/lib/ruby/gems/1.8/gems/simply_stored-0.3.6/lib/simply_stored/instance_methods.rb:11:in `=='
```

this comes as the equals method (==) does not check whether _other_ is an simply stored object. So any object is asked for its __id_-method which of course is not available for objects of foreign classes.

So instead of 

```
def ==(other)
    other._id == _id && other._rev == _rev
end
```

just do

```
def ==(other)
    other.kind_of?(SimplyStored::Couch) && other._id == _id && other._rev == _rev
end
```

and the problem is solved.

**Comment by jweiss** [comment]
Fixed in http://github.com/peritor/simply_stored/commit/6acef52b5deec28f79ee7d8fca6946f509c1b774

Thanks!
